version: "3.8"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_USER: admin_ovo
      POSTGRES_PASSWORD: Admn_1588946
      POSTGRES_DB: Ovosad_db
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin_ovo"]
      interval: 10s
      timeout: 5s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf


  parser:
    build: ./parser
    container_name: parser
    environment:
      - PG_USER=admin_ovo
      - PG_PASS=Admn_1588946
      - PG_DB=Ovosad_db
      - PG_HOST=timescaledb
    depends_on:
      - mosquitto
      - timescaledb

  backend:
    build: ./backend
    container_name: backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - PG_USER=admin_ovo
      - PG_PASS=Admn_1588946
      - PG_DB=Ovosad_db
      - PG_HOST=timescaledb
    depends_on:
      - timescaledb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  timescaledb_data: